<option value="" selected>Select a timezone</option>
<option value="-12 hours">(GMT -12 hours) Eniwetok, Kwajalein</option>
<option value="-11 hours">(GMT -11 hours) Midway Island, Samoa</option>
<option value="-10 hours">(GMT -10 hours) Hawaii</option>
<option value="-09 hours -50 mins">(GMT -9:30) Taiohae</option>
<option value="-09 hours">(GMT -9 hours) Alaska</option>
<option value="-08 hours">(GMT -8 hours) Pacific Time (US &amp; Canada)</option>
<option value="-07 hours">(GMT -7 hours) Mountain Time (US &amp; Canada)</option>
<option value="-06 hours">(GMT -6 hours) Central Time (US &amp; Canada), Mexico City</option>
<option value="-05 hours">(GMT -5 hours) Eastern Time (US &amp; Canada), Bogota, Lima</option>
<option value="-04 hours -50 mins">(GMT -4:30) Caracas</option>
<option value="-04 hours">(GMT -4 hours) Atlantic Time (Canada), Caracas, La Paz</option>
<option value="-03 hours -50 mins">(GMT -3:30) Newfoundland</option>
<option value="-03 hours">(GMT -3 hours) Brazil, Buenos Aires, Georgetown</option>
<option value="-02 hours">(GMT -2 hours) Mid-Atlantic</option>
<option value="-01 hours">(GMT -1 hours) Azores, Cape Verde Islands</option>
<option value="+00 hours">(GMT) Western Europe Time, London, Lisbon, Casablanca</option>
<option value="+01 hours">(GMT +1 hours) Brussels, Copenhagen, Madrid, Paris</option>
<option value="+02 hours">(GMT +2 hours) Kaliningrad, South Africa</option>
<option value="+03 hours">(GMT +3 hours) Baghdad, Riyadh, Moscow, St. Petersburg</option>
<option value="+03 hours +50 mins">(GMT +3:30) Tehran</option>
<option value="+04 hours">(GMT +4 hours) Abu Dhabi, Muscat, Baku, Tbilisi</option>
<option value="+04 hours +50 mins">(GMT +4:30) Kabul</option>
<option value="+05 hours">(GMT +5 hours) Ekaterinburg, Islamabad, Karachi, Tashkent</option>
<option value="+05 hours +50 mins">(GMT +5:30) Bombay, Calcutta, Madras, New Delhi</option>
<option value="+05:75">(GMT +5:45) Kathmandu, Pokhara</option>
<option value="+06 hours">(GMT +6 hours) Almaty, Dhaka, Colombo</option>
<option value="+06 hours +50 mins">(GMT +6:30) Yangon, Mandalay</option>
<option value="+07 hours">(GMT +7 hours) Bangkok, Hanoi, Jakarta</option>
<option value="+08 hours">(GMT +8 hours) Beijing, Perth, Singapore, Hong Kong</option>
<option value="+08:75">(GMT +8:45) Eucla</option>
<option value="+09 hours">(GMT +9 hours) Tokyo, Seoul, Osaka, Sapporo, Yakutsk</option>
<option value="+09 hours +50 mins">(GMT +9:30) Adelaide, Darwin</option>
<option value="+10 hours">(GMT +10 hours) Eastern Australia, Guam, Vladivostok</option>
<option value="+10 hours +50 mins">(GMT +10:30) Lord Howe Island</option>
<option value="+11 hours">(GMT +11 hours) Magadan, Solomon Islands, New Caledonia</option>
<option value="+11 hours +50 mins">(GMT +11:30) Norfolk Island</option>
<option value="+12 hours">(GMT +12 hours) Auckland, Wellington, Fiji, Kamchatka</option>
<option value="+12 hours +75 mins">(GMT +12:45) Chatham Islands</option>
<option value="+13 hours">(GMT +13 hours) Apia, Nukualofa</option>
<option value="+14 hours">(GMT +14 hours) Line Islands, Tokelau</option>
